image: python:3.9

stages:
  - run_python_code

before_script:
  - apt-get update -y
  - apt-get install -y wget unzip
  - wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.85/win64/chrome-win64.zip
  - ls
  - unzip chrome-win64.zip -d /opt/
  - ln -s /opt/chrome-linux/chrome /usr/bin/chrome2
  - pip install -r requirements.txt
run_python_code:
  stage: run_python_code
  script:
    - echo "Running Python code"
    - python3 amazon_mapping_data.py
