stages:
  - run_python_code

run_python_code:
  stage: run_python_code
  script:
    - echo "Running Python code"
    - python amazon_mapping_data.py  # Replace with the actual script name
  only:
    - schedules
