image: python:3.9

stages:
  - run_python_code

before_script:
  - pip install -r requirements.txt

run_python_code:
  stage: run_python_code
  script:
    - echo "Running Python code"
    - python3 amazon_mapping_data.py
